# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
    # Container registry service connection established during pipeline creation
    dockerRegistryServiceConnection: '{{ containerRegistryConnection.Id }}'
    imageRepository: 'javascriptdocker'
    containerRegistry: 'apdemo13.azurecr.io'
    dockerfilePath: '$(Build.SourcesDirectory)/app/Dockerfile'
    tag: '$(Build.BuildId)'

    # Agent VM image name
    vmImageName: 'ubuntu-latest'
stages:
  -  stage: Build
     displayName: Build and push stage
  
