# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  GOBIN:  '$(C:/Users/cbnits-158/go)/bin' # Go binaries path
  GOROOT: '/usr/local/go1.11' # Go installation path
  GOPATH: '$(system.defaultWorkingDirectory)/C:/Users/cbnits-158/go' # Go workspace path
  modulePath: '$(C:/Users/cbnits-158/go)/src/github.com/$(build.sudipto13/DemoProject)'

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: CopyFiles@2
  inputs:
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
- task: GoTool@0
  inputs:
    version: '1.15'
- task: Go@0
  inputs:
    command: 'build'
    arguments: 'd'
    workingDirectory: '$(Build.ArtifactStagingDirectory)/main'



